// unity build batch 9
#include "loop_ret.das.cpp"
#include "make_default.das.cpp"
#include "make_handle.das.cpp"
#include "make_local.das.cpp"
#include "make_struct_with_clone.das.cpp"
#include "map_to_a.das.cpp"
#include "mat_crash.das.cpp"
#include "mat_ctors.das.cpp"
#include "mat_let_handle.das.cpp"
#include "math.das.cpp"
