// unity build batch 10
#include "memzero.das.cpp"
#include "method_semantic.das.cpp"
#include "mksmart_zero.das.cpp"
#include "module.das.cpp"
#include "module_vis_fail.das.cpp"
#include "move_lambda_local_ref.das.cpp"
#include "named_call.das.cpp"
#include "new_and_init.das.cpp"
#include "new_delete.das.cpp"
#include "new_with_init.das.cpp"
