// unity build batch 2
#include "aot_const_ptr.das.cpp"
#include "apply_macro_example.das.cpp"
#include "array.das.cpp"
#include "array_comprehension.das.cpp"
#include "array_reader_example.das.cpp"
#include "at_safeat_field_safefield_operators.das.cpp"
#include "auto_infer.das.cpp"
#include "auto_ref_and_move_ret.das.cpp"
#include "bin_serializer.das.cpp"
#include "bitfields.das.cpp"
