// unity build batch 7
#include "hint_macros_example.das.cpp"
#include "ifnn.das.cpp"
#include "include.das.cpp"
#include "infer_alias_and_alias_ctor.das.cpp"
#include "infer_alias_argument.das.cpp"
#include "infer_remove_ref_const.das.cpp"
#include "init_script.das.cpp"
#include "inscope_return_inscope.das.cpp"
#include "int2_crash.das.cpp"
#include "int_types.das.cpp"
