// unity build batch 11
#include "null_struct_init.das.cpp"
#include "oop.das.cpp"
#include "operator_overload.das.cpp"
#include "operators.das.cpp"
#include "override.das.cpp"
#include "pack_and_unpack.das.cpp"
#include "partial_specialization.das.cpp"
#include "peek_and_modify_string.das.cpp"
#include "persistent.das.cpp"
#include "ptr_index.das.cpp"
