// unity build batch 5
#include "each_std_vector.das.cpp"
#include "enum.das.cpp"
#include "enum_total_test.das.cpp"
#include "fastcall_crash.das.cpp"
#include "finalizer_in_module.das.cpp"
#include "finally.das.cpp"
#include "fio.das.cpp"
#include "foo_bar.das.cpp"
#include "for-loop.das.cpp"
#include "for_array_with_1_element.das.cpp"
