#pragma once

#include "Core/Log.hpp"
#include "ImGui/ImGuiFileDialog.h"
#include "ImGui/imgui.h"
#include "ImGui/icons_font_awesome.h"
#include "Rendering/Model.h"
#include "Rendering/Pipelines/BuiltIn/DebugDrawPipeline.h"
#include "Rendering/Pipelines/BuiltIn/VectorPipeline.h"
#include "Rendering/Pipelines/PipelineStageRenderers/MeshRenderer.h"
#include "Assets/TextureAssetFactory.h"
#include "Assets/ShaderStageBinaryAssetFactory.h"
#include "ECS/TransformSystem.h"
#include "ECS/MeshSystem.h"
#include "ECS/CameraSystem.h"
#include "ECS/MaterialSystem.h"
#include "ECS/LightSystem.h"