//
// Created by liam_ on 10/10/2023.
//
#include "JoltMonoBind.h"
#include "Core/Log.hpp"

void harmony::JoltMonoInternalMethodProvider::BindInternalMethods()
{
/*
    JPH_Init
    JPH_Shutdown
    JPH_SetAssertFailureHandler
    JPH_TempAllocatorMalloc_Create
    JPH_TempAllocator_Create
    JPH_TempAllocator_Destroy
    JPH_JobSystemThreadPool_Create
    JPH_JobSystemSingleThreaded_Create
    JPH_JobSystem_Destroy
    JPH_BroadPhaseLayerInterface_Create
    JPH_BroadPhaseLayerInterface_Destroy
    JPH_ObjectVsBroadPhaseLayerFilter_Create
    JPH_ObjectVsBroadPhaseLayerFilter_Destroy
    JPH_ObjectLayerPairFilter_Create
    JPH_ObjectLayerPairFilter_Destroy
    JPH_BroadPhaseLayerFilter_Create
    JPH_BroadPhaseLayerFilter_Destroy
    JPH_ObjectLayerFilter_Create
    JPH_ObjectLayerFilter_Destroy
    JPH_BodyFilter_Create
    JPH_BodyFilter_Destroy
    JPH_ShapeSettings_Destroy
    JPH_ConvexShapeSettings_GetDensity
    JPH_ConvexShapeSettings_SetDensity
    JPH_ConvexShape_GetDensity
    JPH_ConvexShape_SetDensity
    JPH_BoxShapeSettings_Create
    JPH_BoxShapeSettings_CreateShape
    JPH_BoxShape_Create
    JPH_BoxShape_GetHalfExtent
    JPH_BoxShape_GetVolume
    JPH_BoxShape_GetConvexRadius
    JPH_SphereShapeSettings_Create
    JPH_SphereShapeSettings_CreateShape
    JPH_SphereShapeSettings_GetRadius
    JPH_SphereShapeSettings_SetRadius
    JPH_TriangleShapeSettings_Create
    JPH_CapsuleShapeSettings_Create
    JPH_CapsuleShape_Create
    JPH_CapsuleShape_GetRadius
    JPH_CapsuleShape_GetHalfHeightOfCylinder
    JPH_CylinderShapeSettings_Create
    JPH_CylinderShape_Create
    JPH_CylinderShape_GetRadius
    JPH_CylinderShape_GetHalfHeight
    JPH_ConvexHullShapeSettings_CreateShape
    JPH_ConvexHullShapeSettings_Create
    JPH_MeshShapeSettings_Create
    JPH_MeshShapeSettings_Create2
    JPH_MeshShapeSettings_Sanitize
    JPH_MeshShapeSettings_CreateShape
    JPH_HeightFieldShapeSettings_Create
    JPH_MeshShapeSettings_DetermineMinAndMaxSample
    JPH_MeshShapeSettings_CalculateBitsPerSampleForError
    JPH_TaperedCapsuleShapeSettings_Create
    JPH_CompoundShapeSettings_AddShape
    JPH_CompoundShapeSettings_AddShape2
    JPH_StaticCompoundShapeSettings_Create
    JPH_MutableCompoundShapeSettings_Create
    JPH_Shape_Destroy
    JPH_Shape_GetLocalBounds
    JPH_Shape_GetMassProperties
    JPH_Shape_GetCenterOfMass
    JPH_Shape_GetInnerRadius
    JPH_SphereShape_Create
    JPH_SphereShape_GetRadius
    JPH_BodyCreationSettings_Create
    JPH_BodyCreationSettings_Create2
    JPH_BodyCreationSettings_Create3
    JPH_BodyCreationSettings_Destroy
    JPH_BodyCreationSettings_GetLinearVelocity
    JPH_BodyCreationSettings_SetLinearVelocity
    JPH_BodyCreationSettings_GetAngularVelocity
    JPH_BodyCreationSettings_SetAngularVelocity
    JPH_BodyCreationSettings_GetMotionType
    JPH_BodyCreationSettings_SetMotionType
    JPH_BodyCreationSettings_GetAllowedDOFs
    JPH_BodyCreationSettings_SetAllowedDOFs
    JPH_SoftBodyCreationSettings_Create
    JPH_ConstraintSettings_Destroy
    JPH_Constraint_Destroy
    JPH_Constraint_GetConstraintSettings
    JPH_Constraint_GetEnabled
    JPH_Constraint_SetEnabled
    JPH_TwoBodyConstraint_GetBody1
    JPH_TwoBodyConstraint_GetBody2
    JPH_TwoBodyConstraint_GetConstraintToBody1Matrix
    JPH_TwoBodyConstraint_GetConstraintToBody2Matrix
    JPH_PointConstraintSettings_Create
    JPH_PointConstraintSettings_GetSpace
    JPH_PointConstraintSettings_SetSpace
    JPH_PointConstraintSettings_GetPoint1
    JPH_PointConstraintSettings_SetPoint1
    JPH_PointConstraintSettings_GetPoint2
    JPH_PointConstraintSettings_SetPoint2
    JPH_PointConstraintSettings_CreateConstraint
    JPH_PointConstraint_SetPoint1
    JPH_PointConstraint_SetPoint2
    JPH_DistanceConstraintSettings_Create
    JPH_DistanceConstraintSettings_GetPoint1
    JPH_DistanceConstraintSettings_SetPoint1
    JPH_DistanceConstraintSettings_GetPoint2
    JPH_DistanceConstraintSettings_SetPoint2
    JPH_DistanceConstraintSettings_CreateConstraint
    JPH_HingeConstraintSettings_Create
    JPH_HingeConstraintSettings_GetPoint1
    JPH_HingeConstraintSettings_SetPoint1
    JPH_HingeConstraintSettings_GetPoint2
    JPH_HingeConstraintSettings_SetPoint2
    JPH_HingeConstraintSettings_CreateConstraint
    JPH_SliderConstraintSettings_Create
    JPH_SliderConstraintSettings_SetSliderAxis
    JPH_SliderConstraintSettings_CreateConstraint
    JPH_PhysicsSystem_Create
    JPH_PhysicsSystem_Destroy
    JPH_PhysicsSystem_Init
    JPH_PhysicsSystem_OptimizeBroadPhase
    JPH_PhysicsSystem_Update
    JPH_PhysicsSystem_SetContactListener
    JPH_PhysicsSystem_SetBodyActivationListener
    JPH_PhysicsSystem_GetNumBodies
    JPH_PhysicsSystem_GetNumActiveBodies
    JPH_PhysicsSystem_GetMaxBodies
    JPH_PhysicsSystem_GetGravity
    JPH_PhysicsSystem_SetGravity
    JPH_PhysicsSystem_AddConstraint
    JPH_PhysicsSystem_RemoveConstraint
    JPH_PhysicsSystem_AddConstraints
    JPH_PhysicsSystem_RemoveConstraints
    JPH_PhysicsSystem_GetBodyInterface
    JPH_PhysicsSystem_GetBodyInterfaceNoLock
    JPH_BodyInterface_CreateBody
    JPH_BodyInterface_CreateSoftBody
    JPH_BodyInterface_CreateAndAddBody
    JPH_BodyInterface_CreateBodyWithID
    JPH_BodyInterface_CreateBodyWithoutID
    JPH_BodyInterface_DestroyBody
    JPH_BodyInterface_DestroyBodyWithoutID
    JPH_BodyInterface_AssignBodyID
    JPH_BodyInterface_AssignBodyID2
    JPH_BodyInterface_UnassignBodyID
    JPH_BodyInterface_AddBody
    JPH_BodyInterface_RemoveBody
    JPH_BodyInterface_GetLinearVelocity
    JPH_BodyInterface_SetLinearVelocity
    JPH_BodyInterface_GetCenterOfMassPosition
    JPH_BodyInterface_IsActive
    JPH_BodyInterface_IsAdded
    JPH_BodyInterface_GetBodyType
    JPH_BodyInterface_GetMotionType
    JPH_BodyInterface_SetMotionType
    JPH_BodyInterface_GetMotionQuality
    JPH_BodyInterface_SetMotionQuality
    JPH_BodyInterface_GetRestitution
    JPH_BodyInterface_SetRestitution
    JPH_BodyInterface_GetFriction
    JPH_BodyInterface_SetFriction
    JPH_BodyInterface_SetPosition
    JPH_BodyInterface_GetPosition
    JPH_BodyInterface_SetRotation
    JPH_BodyInterface_GetRotation
    JPH_BodyInterface_SetPositionAndRotation
    JPH_BodyInterface_SetPositionAndRotationWhenChanged
    JPH_BodyInterface_SetPositionRotationAndVelocity
    JPH_BodyInterface_SetShape
    JPH_BodyInterface_NotifyShapeChanged
    JPH_BodyInterface_ActivateBody
    JPH_BodyInterface_DeactivateBody
    JPH_BodyInterface_SetObjectLayer
    JPH_BodyInterface_GetObjectLayer
    JPH_BodyInterface_GetWorldTransform // RMatrix4x4
    JPH_BodyInterface_GetCenterOfMassTransform // RMatrix4x4
    JPH_BodyInterface_MoveKinematic
    JPH_BodyInterface_SetLinearAndAngularVelocity
    JPH_BodyInterface_GetLinearAndAngularVelocity
    JPH_BodyInterface_AddLinearVelocity
    JPH_BodyInterface_AddLinearAndAngularVelocity
    JPH_BodyInterface_SetAngularVelocity
    JPH_BodyInterface_GetAngularVelocity
    JPH_BodyInterface_GetPointVelocity
    JPH_BodyInterface_AddForce
    JPH_BodyInterface_AddForce2
    JPH_BodyInterface_AddTorque
    JPH_BodyInterface_AddForceAndTorque
    JPH_BodyInterface_AddImpulse
    JPH_BodyInterface_AddImpulse2
    JPH_BodyInterface_AddAngularImpulse
    JPH_BodyInterface_GetInverseInertia
    JPH_BodyInterface_SetGravityFactor
    JPH_BodyInterface_GetGravityFactor
    JPH_BodyInterface_InvalidateContactCache
    JPH_BodyInterface_SetUserData
    JPH_BodyInterface_GetUserData
    JPC_PhysicsSystem_GetBodyLockInterface
    JPC_PhysicsSystem_GetBodyLockInterfaceNoLock
    JPH_BodyLockInterface_LockRead
    JPH_BodyLockInterface_UnlockRead
    JPH_BodyLockInterface_LockWrite
    JPH_BodyLockInterface_UnlockWrite
    JPH_MotionProperties_SetLinearDamping
    JPH_MotionProperties_GetLinearDamping
    JPH_MotionProperties_SetAngularDamping
    JPH_MotionProperties_GetAngularDamping
    JPH_MotionProperties_GetInverseMassUnchecked
    JPH_MotionProperties_SetMassProperties
    JPC_PhysicsSystem_GetNarrowPhaseQuery
    JPC_PhysicsSystem_GetNarrowPhaseQueryNoLock
    JPH_NarrowPhaseQuery_CastRay
    JPH_Body_GetID
    JPH_Body_GetBodyType
    JPH_Body_GetWorldSpaceBounds
    JPH_Body_IsActive
    JPH_Body_IsStatic
    JPH_Body_IsKinematic
    JPH_Body_IsDynamic
    JPH_Body_IsSensor
    JPH_Body_SetIsSensor
    JPH_Body_GetMotionProperties
    JPH_Body_GetMotionType
    JPH_Body_SetMotionType
    JPH_Body_GetAllowSleeping
    JPH_Body_SetAllowSleeping
    JPH_Body_GetFriction
    JPH_Body_SetFriction
    JPH_Body_GetRestitution
    JPH_Body_SetRestitution
    JPH_Body_GetPosition
    JPH_Body_GetRotation
    JPH_Body_GetCenterOfMassPosition
    JPH_Body_GetWorldTransform
    JPH_Body_GetCenterOfMassTransform
    JPH_Body_GetLinearVelocity
    JPH_Body_SetLinearVelocity
    JPH_Body_GetAngularVelocity
    JPH_Body_SetAngularVelocity
    JPH_Body_AddForce
    JPH_Body_AddForceAtPosition
    JPH_Body_AddTorque
    JPH_Body_GetAccumulatedForce
    JPH_Body_GetAccumulatedTorque
    JPH_Body_AddImpulse
    JPH_Body_AddImpulseAtPosition
    JPH_Body_AddAngularImpulse
    JPH_Body_SetUserData
    JPH_Body_GetUserData
    JPH_ContactListener_Create
    JPH_ContactListener_Destroy
    JPH_BodyActivationListener_Create
    JPH_BodyActivationListener_Destroy
*/
}

harmony::JoltMonoInternalMethodProvider::JoltMonoInternalMethodProvider() {

}
